platform :ios, '13.0'
pod 'YandexMobileAds', '7.12.1'
pod 'GoogleYandexMobileAdsAdapters'
pod 'UnityAdsYandexMobileAdsAdapters'
pod 'AppLovinYandexMobileAdsAdapters'
pod 'IronSourceYandexMobileAdsAdapters'
pod 'MintegralYandexMobileAdsAdapters'
pod 'MyTargetYandexMobileAdsAdapters'
#pod 'VungleYandexMobileAdsAdapters' # not work
pod 'BigoADSYandexMobileAdsAdapters'
#pod 'YandexMobileAdsMediationExtras' # not work


