platform :ios, '13.0'
pod 'YandexMobileAds', '7.11.1'
pod 'GoogleYandexMobileAdsAdapters'
#pod 'UnityYandexMobileAdsAdapters'
pod 'AppLovinYandexMobileAdsAdapters'
pod 'IronSourceYandexMobileAdsAdapters'
pod 'MintegralYandexMobileAdsAdapters'
pod 'MyTargetYandexMobileAdsAdapters'
#pod 'BigoADSYandexMobileAdsAdapters', '4.0.4.0' OMSDK_Bigosg.framework/OMSDK_Bigosg' (no such file)
#pod 'YandexMobileAdsMediationExtras' # с ним не хочет